### ISSUE TITLE
Seems a bad idea to mess with dnsmasq and haproxy on the host.  

### ISSUE THREAD

**Issue by bayeslearner** [ozchamo/YAKKO#10]
There must be some conflict with the host which is a fedora 38 vanilla.  Would be nice if dnsmasq and haproxy are virtual as well.  The only thing that would exist on the host are ports tunnel into a virtual jumpbox.

**Comment by ozchamo** [comment]
I pondered over that for a long time. What made me decide this path is that running this on the host makes the services available both to the host AND to other clients on the network transparently, in particular with  haproxy as it acts as a bridge all they way. The big gotcha is that KVM does not permit (I can't find a better word) communication between the host and the VMs if they all talk to the same public network (unless you have 'hairpinning' capable switch (!) or you create a bridge on your server and replace a lot of complexity. And - I chose the path of least resistance because building a VM with capability  for DNSmasq and HAproxy etc etc was going to require additional work... I haven't given up on the idea though, but perhaps you might want to try the OpenShift assisted installer if not?

**Comment by bayeslearner** [comment]
There are dedicated third party tools that do that.  I use twingate which allows you expose networks anywhere you want, I heard tailgate is good (but works differently)

**Comment by ozchamo** [comment]
Hi again bayeslearner  - you will be pleased to know that you have given me the motivation to code YAKKO bypassing the internal setup of NetworkManager/dnsmasq. I am testing it right now and you will see this come up in the next week or so. I am testing.... and I am trying to find the time to document after that :)
