### ISSUE TITLE
[FR] Add ops command for adding additional worker nodes

### ISSUE THREAD

**Issue by aenertia** [ozchamo/YAKKO#2]
As per the title, add worker node ; I tried manually deciphering your bash but gave up (such is the nature of bash ;) to add it myself but the way you enumerate virsh definitions and cycle through makes it quite a big refactor.

**Comment by aenertia** [comment]
This also would allow additional operators like OCS (with manual poking of the libvirt definitions and adding additional disks to the workers) etc.

**Comment by ozchamo** [comment]
I love your request - it means you got it to work and want more! I'm not sure that my home lab has enough resources as is to run OCS but I will take a look over the next few weeks. Remember though that since YAKKO makes it trivial to build and rebuild clusters for lab purposes, it's not hard to adjust some of the initial settings to have a larger cluster built. 
Would you find it useful to have an ops call to add a node - and perhaps a switch to specify it as worker or infrastructure?

**Comment by ozchamo** [comment]
Done, see yakko infra addnode!
